### ISSUE TITLE
Install Meilisearch on Platform.sh in a Symfony project (with the Meilisearch-Symfony Bundle)

### ISSUE THREAD

**Issue by digitimage** [platformsh-templates/meilisearch#9]
I'm trying to install Meilisearch with a Symfony application but I can't. I use the [official meilisearch symfony bundle](https://github.com/meilisearch/meilisearch-symfony) which requires a url to communicate with the meilisearch server. Can anyone help me ? I tried this:

at root:
```
// .platform.app.yaml
relationships:
  meilisearch: "meilisearch:http"   # I don't know if it is necessary
```

in a /meilisearch/ subdirectory:
```
// meilisearch/.platform.app.yaml  # inspired by this template
name: "meilisearch"
type: php:8.2
hooks:
  build: |
    curl -L https://install.meilisearch.com | sh
    chmod +x meilisearch
web:
  commands:
    start: "./meilisearch --http-addr localhost:${PORT}"
```

the meilisearch-symfony bundle configuration:
```
// config/packages/meilisearch.yaml
meilisearch:
  url: "http://127.0.0.1:7700" # URL of the Meilisearch server (mandatory)
```
As the URL, I tried also http://localhost:7700 but it failed too.
Thanks for your help
Cyril
